### ISSUE TITLE
_validate_compute_parameters does not throw error if cell tensor is zero, resulting in potential = nan

### ISSUE THREAD

**Issue by tulga-rdn** [lab-cosmo/torch-pme#115]
Basically TSIA.  I think we need to throw an error in `_validate_compute_parameters` if the cell tensor is a zero tensor (which happens if no cell info is present in the `.xyz` dataset). The calculators return potentials equal to `nan` in this case

**Comment by PicoCentauri** [comment]
Thanks for the issue!

Yes something like here

https://github.com/lab-cosmo/torch-pme/blob/ffc689c020fedfe2aaf192c8dd38d223f62d910d/src/torchpme/utils/tuning/__init__.py#L132-L136

should fix this. But the test should only be applied if the given `potential` is range separated. If not we have no fourier space part and the cell can be zero. We usually check this fast with a statement like

```python
if self.potential.smearing is None:
    ...
```

However the method 

https://github.com/lab-cosmo/torch-pme/blob/ffc689c020fedfe2aaf192c8dd38d223f62d910d/src/torchpme/calculators/calculator.py#L181-L188

is static and has no idea about `self.potential`. To solve this one should make this again a normal method and add a test after the device check of the cell

https://github.com/lab-cosmo/torch-pme/blob/ffc689c020fedfe2aaf192c8dd38d223f62d910d/src/torchpme/calculators/calculator.py#L212-L216

**Comment by tulga-rdn** [comment]
Sure, on it
