### ISSUE TITLE
metatensor integration - neighbor list 

### ISSUE THREAD

**Issue by ceriottm** [lab-cosmo/torch-pme#61]
it looks to me (based on examples) that the metatensor wrappers use a separate neighbor list argument to the calculator.forward. Given that https://docs.metatensor.org/latest/atomistic/reference/systems.html#metatensor.torch.atomistic.System has a way to incorporate neighbor list data, shouldn't we do that?

**Comment by PicoCentauri** [comment]
A metatensor model is available in the docs since PR #99
