### ISSUE TITLE
Incorrect determination of k-space cutoff for Ewald calculator?

### ISSUE THREAD

**Issue by sirmarcel** [lab-cosmo/torch-pme#78]
Hello, I have a question about the Ewald calculator, in particular in the k-grid determination.

This is what is done in `ewald.py`:

```python
k_cutoff = 2 * torch.pi / self.lr_wavelength

# Compute number of times each basis vector of the reciprocal space can be
# scaled until the cutoff is reached
basis_norms = torch.linalg.norm(cell, dim=1)
ns_float = k_cutoff * basis_norms / 2 / torch.pi
ns = torch.ceil(ns_float).long()

```

But my understanding is that we're trying to constrain the wavelength of the k-vectors in each direction.

They are of the form `n_a * reciprocal_cell_vectors_a`, i.e. a natural number prefactor (because of pbc) times reciprocal lattice vector (which are the rows of `inv(cell).T * 2 * pi`). The wavelength in each direction is therefore `1 / (n | b_a|)` where we call `b_a` the rows of `inv(cell).T` (i.e. without the `2 pi` prefactor). We want `1 / (n | b_a|) <= lr_wavelength =  λ`, so `n <= 1 / ( λ | b_a |)`. I.e. we can determine `n` as the `ceil` of `1/ (lr_wavelength * |b_a|`.

But! `1/|b_a|` is not what is computed up there, because we're using `cell` instead of `inv(cell)`. This makes no difference in orthorhombic systems, because there `|b_a| = 1/L_a` (with `L_a` the `basis_norms` as defined above). But in non-orthorhombic cases, they differ, and our cutoffs are therefore determined incorrectly.

Am I understanding this correctly, or did I miss something?

**Comment by PicoCentauri** [comment]
Maybe @kvhuguenin and @GardevoirX do you have capacities to look into this? This might be related to the issues we are seeing with the new upcoming tuning code.

**Comment by sirmarcel** [comment]
I think @kvhuguenin told me that this is correct. I do not know why 😔

**Comment by PicoCentauri** [comment]
Okay...
